name: Keep My Cookie Alive
on:
  schedule:
    - cron: '*/10 * * * *' # يشتغل كل 10 دقائق
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Run Heartbeat Script
        run: |
          python3 main.py
